config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
    redirect_to posts_path
  else
    render action:'new'
  end
  end

  def show
    @post = Post.find(params[:id])
  end
  
  def destroy
  @post = Post.find(params[:id])
  @post.destroy

  redirect_to posts_path
end

  def update
  @post = Post.find(params[:id])

  if @post.update(post_params)
    redirect_to @post
  else
    render 'edit'
  end
end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div id="every">
<% if @post.errors.any? %>
  <div class="form_errors">
    <h3>Errors</h3>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @post do |f| %>
<div>
    <p><%= f.label :title  %></p>
    <%= f.text_field :title, placeholder: "Title" %>
  </div>
  <div>
    <p><%= f.label :content  %></p>
    <%= f.text_field :content, placeholder: "New ToDo" %>
  </div>
  <%= submit_tag %>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit ToDo</h1>

<%= render 'form' %>

 <%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="head">
<h1>To Dos</h1>
</div>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Created_at</th>
    <th>Updated_at</th>
  </tr>

<% @posts.each do |post| %>
<tr>
  <td><%= post.title  %></td>
  <td><%= post.content %></td>
  <td><%= post.created_at %></td>
  <td><%= post.updated_at %></td>
  <td><%= link_to 'Show', post_path(post) %></td>
  <td><%= link_to 'Edit', edit_post_path(post) %></td>
  <td><%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

<% end %>
</table>

<div id= "link">
<%= link_to 'New ToDo', new_post_path %>
</div>

app/views/posts/new.html.erb
<h1>New ToDo</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div id="show">
  <h1>ToDo</h1>
<h2><%= @post.title.upcase %></h2>
<p><%=@post.content %></p>
<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Destroy', post_path,
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', posts_path %>
</div>